apiVersion: apps/v1
kind: Deployment
metadata:
  name: authy
  namespace: {{ default "authy" .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: authy
  replicas: 1
  template:
    metadata:
      labels:
        app: authy
    spec:
      containers:
      - name: authy
        image: {{ .Values.image.registry }}.azurecr.io/{{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        ports:
        - containerPort: 4000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: authy-config
              key: DATABASE_URL
        - name: SECRET_KEY_BASE
          valueFrom:
            configMapKeyRef:
              name: authy-config
              key: SECRET_KEY_BASE
        - name: PHX_HOST
          valueFrom:
            configMapKeyRef:
              name: authy-config
              key: PHX_HOST
