apiVersion: apps/v1
kind: Deployment
metadata:
  name: authy
  namespace: {{ default "authy" .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: authy
  replicas: 1
  template:
    metadata:
      labels:
        app: authy
    spec:
      containers:
      - name: authy
        image: {{ .Values.image.registry }}.azurecr.io/{{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        ports:
        - containerPort: 4000
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: authy-postgres-secret
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authy-postgres-secret
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: authy-config
              key: DATABASE_HOST
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: authy-config
              key: DATABASE_NAME
        - name: SECRET_KEY_BASE
          valueFrom:
            configMapKeyRef:
              name: authy-config
              key: SECRET_KEY_BASE
        - name: PHX_HOST
          valueFrom:
            configMapKeyRef:
              name: authy-config
              key: PHX_HOST
        - name: DATABASE_URL
          value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST)/$(DATABASE_NAME)"
