apiVersion: v1
kind: Service
metadata:
  name: authy-service
  namespace: {{ default "authy" .Release.Namespace }}
spec:
  ports:
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: authy
  type: ClusterIP
